openapi: 3.0.1
info:
  title: Account API
  version: 1.0.0
  description: API for managing bank accounts.
servers:
  - url: http://localhost:8081
paths:
  /accounts:
    post:
      summary: Create a new account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '200':
          description: Account created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
    get:
      summary: Get all accounts
      responses:
        '200':
          description: List of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
  /accounts/{id}:
    get:
      summary: Get an account by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Account found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
    delete:
      summary: Delete an account
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Account deleted
  /accounts/{id}/depositar:
    put:
      summary: Deposit into an account
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: amount
          in: query
          required: true
          schema:
            type: number
            format: double
      responses:
        '200':
          description: Deposit successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
  /accounts/{id}/retirar:
    put:
      summary: Withdraw from an account
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: amount
          in: query
          required: true
          schema:
            type: number
            format: double
      responses:
        '200':
          description: Withdrawal successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
        accountNumber:
          type: string
        balance:
          type: number
          format: double
        accountType:
          type: string
          enum:
            - SAVINGS
            - CURRENT
        customerId:
          type: integer
      required:
        - accountNumber
        - balance
        - accountType
        - customerId