spring:
  application:
    name: customer-ms
  datasource:
    url: jdbc:mysql://localhost:3306/customers?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Mancora#1
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true

server:
  port: 8081
  servlet:
    context-path: /customer-ms

accountms:
  base-url: http://localhost:8082/account-ms
